/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package musicplayer;

import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class PlayListForm extends javax.swing.JFrame {

    MP3Player player;
    
    File songFile;
    String currentDirectory="home.user";
    String currentPath;
    
    String imagePath;
    
    boolean repeat=false;
    
    boolean windowCollapsed=false;
    
    
    public PlayListForm() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playListPnl = new javax.swing.JPanel();
        scrolPanePlayList = new javax.swing.JScrollPane();
        tblSongs = new javax.swing.JTable();
        btnAddSongs = new javax.swing.JButton();
        lblPlayListName = new javax.swing.JLabel();
        txtPlayListName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playListPnl.setBackground(new java.awt.Color(7, 63, 86));

        tblSongs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Song Path"
            }
        ));
        scrolPanePlayList.setViewportView(tblSongs);

        btnAddSongs.setText("Add Song");
        btnAddSongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSongsActionPerformed(evt);
            }
        });

        lblPlayListName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPlayListName.setForeground(new java.awt.Color(255, 51, 51));
        lblPlayListName.setText("Play List Name");

        javax.swing.GroupLayout playListPnlLayout = new javax.swing.GroupLayout(playListPnl);
        playListPnl.setLayout(playListPnlLayout);
        playListPnlLayout.setHorizontalGroup(
            playListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrolPanePlayList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(playListPnlLayout.createSequentialGroup()
                .addGroup(playListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playListPnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblPlayListName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlayListName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(playListPnlLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnAddSongs)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        playListPnlLayout.setVerticalGroup(
            playListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playListPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayListName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlayListName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrolPanePlayList, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddSongs)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playListPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playListPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSongsActionPerformed
        
        JFileChooser openFileChooser=new JFileChooser(currentDirectory);
        openFileChooser.setFileFilter(new FileTypeFilter(".mp3","Open MP3 Files Only!"));
        int result=openFileChooser.showOpenDialog(null);
        SongList songList=new SongList();
        if(result== JFileChooser.APPROVE_OPTION){
            songFile=openFileChooser.getSelectedFile();
            
            //add to linked list song path
            
            songList.insertLast(songFile,songFile.getName());
            songList.display();

            
             
             
            //lblPlaying.setText("Playing Now...!"+songFile.getName());
            DefaultTableModel model = (DefaultTableModel)tblSongs.getModel();
            File[] data={songFile};
            model.addRow(data);
             player.addToPlayList(songFile);
            
        player.skipForward();
        currentDirectory=songFile.getAbsolutePath();
        }
       
       
        
        
        
    }//GEN-LAST:event_btnAddSongsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSongs;
    private javax.swing.JLabel lblPlayListName;
    private javax.swing.JPanel playListPnl;
    private javax.swing.JScrollPane scrolPanePlayList;
    private javax.swing.JTable tblSongs;
    private javax.swing.JTextField txtPlayListName;
    // End of variables declaration//GEN-END:variables
}
